USE DBQS;
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('dbo.GSS_Packages_Templates', 'U') IS NOT NULL
	DROP TABLE dbo.GSS_Packages_Templates;
GO

CREATE TABLE dbo.GSS_Packages_Templates (
	Id_Package  VARCHAR(50)  NOT NULL,
	Id_Item     VARCHAR(50)  NOT NULL,
	Modify_By   VARCHAR(50)  NOT NULL,
	Modify_Date DATETIME     NOT NULL,
	Modify_IP   VARCHAR(20)  NOT NULL,
	CONSTRAINT PK_GSS_PACKAGES_TEMPLATES PRIMARY KEY CLUSTERED (
		Id_Package ASC,
		Id_Item ASC
	)
);
GO

ALTER TABLE dbo.GSS_Packages_Templates
ADD CONSTRAINT FK_GSS_PACKAGES_TEMPLATES_PACKAGE
FOREIGN KEY (Id_Package)
REFERENCES dbo.GSS_Cat_Item (Id_Item);
GO

ALTER TABLE dbo.GSS_Packages_Templates
ADD CONSTRAINT FK_GSS_PACKAGES_TEMPLATES_ITEM
FOREIGN KEY (Id_Item)
REFERENCES dbo.GSS_Cat_Item (Id_Item);
GO
